### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by richardtop** [hexagons/Xcode-Progress#1]
Hi Anton, great idea!
I can't compile the app due to the CocoaPods error, I guess, it is somehow related to your environment that is not stored in Git...?

```Bash
richard@Richards-Mac-mini Xcode-Progress-master % pod install
Analyzing dependencies
[!] No podspec found for `LiveValues` in `~/Documents/Code/Frameworks/Production/LiveValues`

[!] Automatically assigning platform `macOS` with version `10.15` on target `Xcode Progress` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
richard@Richards-Mac-mini Xcode-Progress-master % 

```

**Comment by heestand-xyz** [comment]
Hi Richard, thanks!
I've switched from dev pods to online pods, so should work now!
https://github.com/hexagons/Xcode-Progress/blob/master/Podfile
Note that app might need a couple runs before it works, there's some inconsistent PixelBuffer issue.
