### ISSUE TITLE
If window is placed on top of the Xcode progress bar, the image gets copied in the Xcode Progress

### ISSUE THREAD

**Issue by richardtop** [hexagons/Xcode-Progress#2]
![Skärmavbild 2019-12-20 kl  16 03 17](https://user-images.githubusercontent.com/8013017/71259988-6eaf0900-2342-11ea-8498-256cea00455c.png)

**Comment by heestand-xyz** [comment]
Yes, it’s a screen recording, can’t control that, sorry.
